---
parent: V2_finance_defaults_vehicletype
name: V2FinanceDefaultsVehicletypePostCorsConfig
description: Returns default finance data
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /v2/finance/defaults/{VehicleType}
endpoint: /v2/finance/defaults/UNASSIGNED
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Accept: {{@Var.Accept}}'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "Criteria" : {
        "Key" : "{{@Var.Key}}",
        "Name" : "{{@Var.Name}}",
        "Type" : "{{@Var.Type}}",
        "IsDefault" : false,
        "Term" : {
          "Options" : [ {
            "IsDefault" : false,
            "Value" : "{{@RandomInteger}}"
          } ]
        },
        "Deposit" : {
          "Default" : "{{@Var.Default}}",
          "IsRequired" : false,
          "Minimum" : "{{@Var.Minimum}}",
          "Maximum" : "{{@Var.Maximum}}",
          "DefaultIsPercentage" : false,
          "Locale" : {
            "DisplayValue" : "{{@Var.DisplayValue}}"
          },
          "OrderNo" : "{{@Var.OrderNo}}",
          "MaximumAsPercentageOfOtr" : "{{@Var.MaximumAsPercentageOfOtr}}",
          "MinimumAsPercentageOfOtr" : "{{@Var.MinimumAsPercentageOfOtr}}",
          "DefaultAsPercentageOfOtr" : "{{@Var.DefaultAsPercentageOfOtr}}"
        },
        "Mileage" : {
          "Options" : [ {
            "IsDefault" : false,
            "Value" : "{{@RandomInteger}}"
          } ]
        },
        "AdvanceRentals" : {
          "Options" : [ {
            "IsDefault" : false,
            "Value" : "{{@RandomInteger}}"
          } ]
        },
        "MonthlyPrice" : {
          "Min" : "{{@Var.Min}}",
          "Max" : "{{@Var.Max}}"
        },
        "IsPersonalised" : false,
        "RegularPayment" : "{{@Var.RegularPayment}}",
        "PartExchange" : "{{@Var.PartExchange}}",
        "Settlement" : "{{@Var.Settlement}}",
        "CustomerType" : "{{@Var.CustomerType}}",
        "VehicleType" : "{{@Var.VehicleType}}"
      },
      "Vin" : "{{@Var.Vin}}",
      "OfferPrice" : "{{@Var.OfferPrice}}",
      "VehicleType" : "{{@Var.VehicleType}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- OWASP-OriginHeaderScrutiny
- OWASP-API7
- Misconfiguration
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
