---
parent: V1_finance_terms
name: V1FinanceTermsPostCorsConfig
description: Returns finance terms and conditions using the link from Codeweavers
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /v1/finance/terms
endpoint: /v1/finance/terms
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Accept: {{@Var.Accept}}'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "TermsUrl" : "{{@Var.TermsUrl}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- OWASP-OriginHeaderScrutiny
- OWASP-API7
- Misconfiguration
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
